### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by halbmy** [clberube/BISIP#1]
Dear Charles,
great work that can be of value for many SIP people! Thanks for sharing it.
I noticed that it only works for Python 2 (I guess only 2.7 as the pyd is linked against it). However, after long years of coexistence of Python 2 and Python 3, the days of Python 2 are over and all distributions are moving to Python 3 only as planned many years ago. So did we, not distributing any 2.7 stuff anymore.

Making the code compatible with both Python 2 and 3 should be easy using the future module (http://python-future.org) or 2to3 tools. I would appreciate it and I am sure it would increase users a lot.
Thomas

**Comment by clberube** [comment]
Dear Thomas,
I totally agree. I will work on making it compatible in both Python 2 and 3. 
Charles

**Comment by clberube** [comment]
Hello Thomas,
It is now compatible with Python 3. I've been testing it for the past few days on the latest Anaconda distribution with Python 3.6.2 without problems. I also added support for quick installation through `pip`. That should solve the problem with the pyd since it should now build on your machine.
I refer you to the [readme](https://github.com/clberube/BISIP/blob/master/README.md) and Jupyter [notebooks](https://github.com/clberube/BISIP/tree/master/examples) if you would like to see some examples.

Keep in mind this code was initially designed in my free time to help the SIP colleagues at our University since there was no code publicly available then. It is not always practical. Also due to the stochastic nature of the algorithm it is more designed for learning about the data or models than for big production. However, the way its written I think makes it easy to use and easily integrable with other codes so maybe someone out there will find it useful.
I try not to spend too much time on this now if I want to graduate in 2018... but it is a fun project and I will keep updating from time to time.
